export const brandActionTypes = {
  GET_ALL_BRANDS: "BRANDS.GET_ALL",
  GET_BRAND: "BRANDS.GET_BRAND",
  SET_BRAND: "BRANDS.SET_BRAND",
  SET_PAGE_BRANDS: "BRANDS.SET_PAGE",
  SET_LOADING_BRANDS: "BRANDS.SET_LOADING",
  SET_TOTALPAGE_BRANDS: "BRANDS.SET_TOTALPAGE",
  SET_FILTERS_BRANDS: "BRANDS.SET_FILTERS",
};
