export const carActionTypes = {
  GET_ALL_CARS: "CARS.GET_ALL_CARS",
  SET_PAGE_CARS: "CARS.SET_PAGE",
  SET_LOADING_CARS: "CARS.SET_LOADING",
  SET_TOTALPAGE_CARS: "CARS.SET_TOTALPAGE",
  SET_FILTERS_CARS: "CARS.SET_FILTERS",
};
